name: Test
on:
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repository'
              uses: actions/checkout@v2

            - name: 'Composer install'
              run: make composer-install

            - name: 'Run test suite'
              run: make tests